import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../core/floating_action.dart';

class TranslatePage extends StatefulWidget {
  const TranslatePage({Key? key}) : super(key: key);

  @override
  State<TranslatePage> createState() => _TranslatePageState();
}

class _TranslatePageState extends State<TranslatePage> {
  List<String> lastWords = [
    "Bu alanda sadece Excel formüllerinin Türkçe ve İngilizce çevirileri bulunmaktadır. Formüllerin işlevleri ve tanımları için eğitim setlerini takip edebilirsiniz.",
    "ACOS - ACOS",
    "ACOSH - ACOSH",
    "ADRES - ADDRESS",
    "AİÇVERİMORANI - XIRR",
    "ALANSAY - AREAS",
    "ALTTOPLAM - SUBTOTAL",
    "AMORDEGRC - AMORDEGRC",
    "AMORLINC - AMORLINC",
    "ANA_PARA_ÖDEMESİ - PPMT",
    "ANBD - XNPV",
    "ARA - LOOKUP",
    "ASİN - ASIN",
    "ASİNH - ASINH",
    "AŞAĞIYUVARLA - ROUNDDOWN",
    "ATAN - ATAN",
    "ATAN2 - ATAN2",
    "ATANH - ATANH",
    "AY - MONTH",
    "AZALANBAKİYE - DB",
    "BAĞ_DEĞ_DOLU_SAY - COUNTA",
    "BAĞ_DEĞ_SAY - COUNT",
    "BASIKLIK - KURT",
    "BD - PV",
    "BESINIR - GESTEP",
    "BESSELI - BESSELI",
    "BESSELJ - BESSELJ",
    "BESSELK - BESSELK",
    "BESSELY - BESSELY",
    "BETADAĞ - BETADIST",
    "BETATERS - BETAINV",
    "BIN2DEC - BIN2DEC",
    "BIN2HEX - BIN2HEX",
    "BIN2OCT - BIN2OCT",
    "BİLGİ - INFO",
    "BİNOMDAĞ - BINOMDIST",
    "BİRLEŞTİR - CONCATENATE",
    "BOŞLUKSAY - COUNTBLANK",
    "BÖLÜM - QUOTIENT",
    "BUGÜN - TODAY",
    "BUL - FIND",
    "BÜYÜK - LARGE",
    "BÜYÜKHARF - UPPER",
    "BÜYÜME - GROWTH",
    "COS - COS",
    "COSH - COSH",
    "ÇARPIKLIK - SKEW",
    "ÇARPIM - PRODUCT",
    "ÇARPINIM - FACT",
    "ÇEVİR - CONVERT",
    "ÇİFT - EVEN",
    "ÇİFTAZALANBAKİYE - DDB",
    "ÇİFTFAKTÖR - FACTDOUBLE",
    "ÇİFTMİ - ISEVEN",
    "ÇOKTERİMLİ - MULTINOMIAL",
    "D_İÇ_VERİM_ORANI - MIRR",
    "DA - SLN",
    "DAB - VDB",
    "DAKİKA - MINUTE",
    "DAMGA - CHAR",
    "DÇARP - MMULT",
    "DEC2BIN - DEC2BIN",
    "DEC2HEX - DEC2HEX",
    "DEC2OCT - DEC2OCT",
    "DEĞER - PRICE",
    "DEĞERİND - PRICEDISC",
    "DEĞERVADE - PRICEMAT",
    "DEĞİL - NOT",
    "DEĞİŞTİR - REPLACE",
    "DELTA - DELTA",
    "DERECE - DEGREES",
    "DETERMİNANT - MDETERM",
    "DEVRESEL_ÖDEME - PMT",
    "DEVRİK_DÖNÜŞÜM - TRANSPOSE",
    "DİZEY_TERS - MINVERSE",
    "DOĞRU - DOĞRU",
    "DOLAYLI - INDIRECT",
    "DOT - LINEST",
    "DÖRTTEBİRLİK - QUARTILE",
    "DÜŞEYARA - VLOOKUP",
    "EBOŞSA - ISBLANK",
    "EĞER - IF",
    "EĞERSAY - COUNTIF",
    "EĞİLİM - TREND",
    "EĞİM - SLOPE",
    "EHATA - ISERR",
    "EHATALIYSA - ISERROR",
    "ELEMAN - CHOOSE",
    "EMANTIKSALSA - ISLOGICAL",
    "EMETİNDEĞİLSE - ISNONTEXT",
    "EMETİNSE - ISTEXT",
    "ENÇOK_OLAN - MODE",
    "EREFSE - ISREF",
    "ESAYIYSA - ISNUMBER",
    "ETKİN - EFFECT",
    "ETOPLA - SUMIF",
    "EYOKSA - ISNA",
    "FAİZ_ORANI - RATE",
    "FAİZORANI - INTRATE",
    "FAİZTUTARI - IPMT",
    "FDAĞ - FDIST",
    "FISHER - FISHER",
    "FISHERTERS - FISHERINV",
    "FTERS - FINV",
    "FTEST - FTEST",
    "GAMADAĞ - GAMMADIST",
    "GAMALN - GAMMALN",
    "GAMATERS - GAMMAINV",
    "GD - FV",
    "GDPROGRAM - GDPROGRAM",
    "GEOORT - GEOMEAN",
    "GERÇEKFAİZ - ACCRINT",
    "GERÇEKFAİZV - ACCRINTM",
    "GETİRİ - RECEİVED",
    "GÜN - DAY",
    "GÜN360 - DAYS360",
    "GÜVENİRLİK - CONFIDENCE",
    "HAFTANINGÜNÜ - WEEKDAY",
    "HAFTASAY - WEEKNUM",
    "HARORT - HARMEAN",
    "HATA.TİPİ - ERROR.TYPE",
    "HATAİŞLEV - ERF",
    "HEX2BIN - HEX2BIN",
    "HEX2DEC - HEX2DEC",
    "HEX2OCT - HEX2OCT",
    "HİPERGEOMDAĞ - HYPGEOMDIST",
    "HTAHDEĞER - TBILLPRICE",
    "HTAHEŞ - TBILLEQ",
    "HTAHÖDEME - TBILLYIELD",
    "HÜCRE - CELL",
    "ISPMT - ISPMT",
    "İÇ_VERİM_ORANI - IRR",
    "İNDİRİM - DISC",
    "İNDİS - INDEX",
    "İŞARET - SIGN",
    "İŞGÜNÜ - WORKDAY",
    "KAÇINCI - MATCH",
    "KAREKÖK - SQRT",
    "KAREKÖKPİ - SQRTPI",
    "KARMAŞIK - COMPLEX",
    "KAYDIR - OFFSET",
    "KESMENOKTASI - INTERCEPT",
    "KIRP - TRIM",
    "KIRPORTALAMA - TRIMMEAN",
    "KİKAREDAĞ - CHIDIST",
    "KİKARETERS - CHIINV",
    "KİKARETEST - CHITEST",
    "KOD - CODE",
    "KOMBİNASYON - COMBIN",
    "KORELASYON - CORREL",
    "KOVARYANS - COVAR",
    "KÖPRÜ - HYPERLINK",
    "KRİTİKBİNOM - CRITBINOM",
    "KUPONGÜN - COUPDAYS",
    "KUPONGÜNBD - COUPDAYBS",
    "KUPONGÜNDSK - COUPDAYSNC",
    "KUPONGÜNÖKT - COUPPCD",
    "KUPONGÜNSKT - COUPNCD",
    "KUPONSAYI - COUPNUM",
    "KUVVET - POWER",
    "KÜÇÜK - SMALL",
    "KÜÇÜKHARF - LOWER",
    "KYUVARLA - MROUND",
    "LİRA - DOLLAR",
    "LİRAKES - DOLLARFR",
    "LİRAON - DOLLARDE",
    "LN - LN",
    "LOG - LOG",
    "LOG10 - LOG10",
    "LOGNORMDAĞ - LOGNORMDIST",
    "LOGTERS - LOGINV",
    "LOT - LOGEST",
    "M - T",
    "MAK - MAX",
    "MAKA - MAXA",
    "MBUL - SEARCH",
    "METNEÇEVİR - TEXT",
    "MİN - MIN",
    "MİNA - MINA",
    "MOD - MOD",
    "MSÜRE - MDURATION",
    "MUTLAK - ABS",
    "NBD - NPV",
    "NEGBİNOMDAĞ - NEGBINOMDIST",
    "NOMİNAL - NOMINAL",
    "NORMDAĞ - NORMDIST",
    "NORMSDAĞ - NORMSDIST",
    "NORMSTERS - NORMSINV",
    "NORMTERS - NORMINV",
    "NSAT - TRUNC",
    "OBEB - GCD",
    "OCT2BIN - OCT2BIN",
    "OCT2DEC - OCT2DEC",
    "OCT2HEX - OCT2OCT",
    "OKEK - LCM",
    "OLASILIK - PROB",
    "ORTALAMA - AVERAGE",
    "ORTALAMAA - AVERAGEA",
    "ORTANCA - MEDIAN",
    "ORTSAP - AVEDEV",
    "ÖDEME - YIELD",
    "ÖDEMEİND - YIELDDISC",
    "ÖDEMEVADE - YIELDMAT",
    "ÖZDEŞ - EXACT",
    "ÖZETVERİAL - GETPIVOTDATA",
    "PARÇAAL - MID",
    "PEARSON - PEARSON",
    "PERMÜTASYON - PERMUT",
    "Pİ - PI",
    "POISSON - POISSON",
    "RADYAN - RADIANS",
    "RANK - RANK",
    "RASTGELEARADA - RANDBETWEEN",
    "RKARE - RSQ",
    "ROMEN - ROMAN",
    "S - N",
    "S_SAYI_ÜRET - RAND",
    "SAAT - HOUR",
    "SAĞDAN - RIGHT",
    "SANAL - IMAGINARY",
    "SANBAĞ_DEĞİŞKEN - IMARGUMENT",
    "SANBÖL - IMDIV",
    "SANCOS - IMCOS",
    "SANÇARP - IMPRODUCT",
    "SANÇIKAR - IMSUB",
    "SANEŞLENEK - IMCONJUGATE",
    "SANGERÇEK - IMREAL",
    "SANİYE - SECOND",
    "SANKAREKÖK - IMSQRT",
    "SANKUVVET - IMPOWER",
    "SANLN - IMLN",
    "SANLOG10 - IMLOG10",
    "SANLOG2 - IMLOG2",
    "SANMUTLAK - IMABS",
    "SANSIN - IMSIN",
    "SANTOPLA - IMSUM",
    "SANÜS - IMEXP",
    "SAPKARE - DEVSQ",
    "SATIR - ROW",
    "SATIRSAY - ROWS",
    "SAYIDÜZENLE - FIXED",
    "SAYIYAÇEVİR - VALUE",
    "SERİAY - EDTE",
    "SERİTARİH - EOMONTH",
    "SERİTOPLA - SERIESSUM",
    "SIKLIK - FREQUENCY",
    "SİN - SIN",
    "SİNH - SINH",
    "SOLDAN - LEFT",
    "STANDARTLAŞTIRMA - STANDARDIZE",
    "STDSAPMA - STDEV",
    "STDSAPMAA - STDEVA",
    "STDSAPMAS - STDEVP",
    "STDSAPMASA - STDEVPA",
    "STHYX - STEYX",
    "SÜRE - DURATION",
    "SÜTUN - COLUMN",
    "SÜTUNSAY - COLUMNS",
    "ŞİMDİ - NOW",
    "TABANAYUVARLA - FLOOR",
    "TAHMİN - FORECAST",
    "TAKSİT_SAYISI - NPER",
    "TAMİŞGÜNÜ - NETWORKDAYS",
    "TAMSAYI - INT",
    "TAN - TAN",
    "TANH - TANH",
    "TARİH - DATE",
    "TARİHSAYISI - DATEVALUE",
    "TAVANAYUVARLA - CEILING",
    "TDAĞ - TDIST",
    "TEK - ODD",
    "TEKMİ - ISODD",
    "TEKSDEĞER - ODDLPRICE",
    "TEKSÖDEME - ODDLYIELD",
    "TEKYDEĞER - ODDFPRICE",
    "TEKYÖDEME - ODDFYIELD",
    "TEMİZ - CLEAN",
    "TOPANAPARA - CUMPRINC",
    "TOPKARE - SUMSQ",
    "TOPLA - SUM",
    "TOPLA.ÇARPIM - SUMPRODUCT",
    "TOPÖDENENFAİZ - CUMIMPT",
    "TOPX2AY2 - SUMX2PY2",
    "TOPX2EY2 - SUMX2MY2",
    "TOPXEY2 - SUMXMY2",
    "TTERS - TINV",
    "TTEST - TTEST",
    "TÜMHATAİŞLEV - ERFC",
    "TÜR - TYPE",
    "UZUNLUK - LEN",
    "ÜS - EXP",
    "ÜSTELDAĞ - EXPONDIST",
    "VAL - DGET",
    "VAR - VAR",
    "VARA - VARA",
    "VARS - VARP",
    "VARSA - VARPA",
    "VE - AND",
    "VSEÇÇARP - DPRODUCT",
    "VSEÇMAK - DMAX",
    "VSEÇMİN - DMIN",
    "VSEÇORT - DAVERAGE",
    "VSEÇSAY - DCOUNT",
    "VSEÇSAYDOLU - DCOUNTA",
    "VSEÇSTDSAPMA - DSTDEV",
    "VSEÇSTDSAPMAS - DSTDEVP",
    "VSEÇTOPLA - DSUM",
    "VSEÇVAR - DVAR",
    "VSEÇVARS - DVARP",
    "WEIBULL - WEIBULL",
    "YADA - OR",
    "YANLIŞ - YANLIŞ",
    "YAT - SYD",
    "YATAYARA - HLOOKUP",
    "YAZIM.DÜZENİ - PROPER",
    "YERİNEKOY - SUBSTITUTE",
    "YIL - YEAR",
    "YILORAN - YEARFRAC",
    "YİNELE - REPT",
    "YOKSAY - NA",
    "YUKARIYUVARLA - ROUNDUP",
    "YUVARLA - ROUND",
    "YÜZDEBİRLİK - PERCENTILE",
    "YÜZDERANK - PERCENTRANK",
    "ZAMAN - TIME",
    "ZAMANSAYISI - TIMEVALUE",
    "ZTEST - ZTEST",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        title: Text(
          "Formül Çevirileri",
          style: GoogleFonts.raleway(color: Colors.black),
        ),
        centerTitle: true,
        actions: [
          IconButton(
              onPressed: () {
                showSearch(
                  context: context,
                  delegate: CustomSearchDelegate(),
                );
              },
              icon: const Icon(Icons.search))
        ],
      ),
      body: Center(
        child: ListView(
          children: [
            SizedBox(
              height: 800,
              child: ListView.builder(
                itemCount: lastWords.length,
                itemBuilder: (context, index) {
                  var result = lastWords[index];
                  return Padding(
                    padding: const EdgeInsets.symmetric(vertical: 5),
                    child: ListTile(
                      leading: const Icon(Icons.pageview_rounded),
                      title: Text(
                        result,
                        style: GoogleFonts.raleway(),
                      ),
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class CustomSearchDelegate extends SearchDelegate {
  List<String> searchTerms = [
    "Bu alanda sadece Excel formüllerinin Türkçe ve İngilizce çevirileri bulunmaktadır. Formüllerin işlevleri ve tanımları için eğitim setlerini takip edebilirsiniz.",
    "ACOS - ACOS",
    "ACOSH - ACOSH",
    "ADRES - ADDRESS",
    "AİÇVERİMORANI - XIRR",
    "ALANSAY - AREAS",
    "ALTTOPLAM - SUBTOTAL",
    "AMORDEGRC - AMORDEGRC",
    "AMORLINC - AMORLINC",
    "ANA_PARA_ÖDEMESİ - PPMT",
    "ANBD - XNPV",
    "ARA - LOOKUP",
    "ASİN - ASIN",
    "ASİNH - ASINH",
    "AŞAĞIYUVARLA - ROUNDDOWN",
    "ATAN - ATAN",
    "ATAN2 - ATAN2",
    "ATANH - ATANH",
    "AY - MONTH",
    "AZALANBAKİYE - DB",
    "BAĞ_DEĞ_DOLU_SAY - COUNTA",
    "BAĞ_DEĞ_SAY - COUNT",
    "BASIKLIK - KURT",
    "BD - PV",
    "BESINIR - GESTEP",
    "BESSELI - BESSELI",
    "BESSELJ - BESSELJ",
    "BESSELK - BESSELK",
    "BESSELY - BESSELY",
    "BETADAĞ - BETADIST",
    "BETATERS - BETAINV",
    "BIN2DEC - BIN2DEC",
    "BIN2HEX - BIN2HEX",
    "BIN2OCT - BIN2OCT",
    "BİLGİ - INFO",
    "BİNOMDAĞ - BINOMDIST",
    "BİRLEŞTİR - CONCATENATE",
    "BOŞLUKSAY - COUNTBLANK",
    "BÖLÜM - QUOTIENT",
    "BUGÜN - TODAY",
    "BUL - FIND",
    "BÜYÜK - LARGE",
    "BÜYÜKHARF - UPPER",
    "BÜYÜME - GROWTH",
    "COS - COS",
    "COSH - COSH",
    "ÇARPIKLIK - SKEW",
    "ÇARPIM - PRODUCT",
    "ÇARPINIM - FACT",
    "ÇEVİR - CONVERT",
    "ÇİFT - EVEN",
    "ÇİFTAZALANBAKİYE - DDB",
    "ÇİFTFAKTÖR - FACTDOUBLE",
    "ÇİFTMİ - ISEVEN",
    "ÇOKTERİMLİ - MULTINOMIAL",
    "D_İÇ_VERİM_ORANI - MIRR",
    "DA - SLN",
    "DAB - VDB",
    "DAKİKA - MINUTE",
    "DAMGA - CHAR",
    "DÇARP - MMULT",
    "DEC2BIN - DEC2BIN",
    "DEC2HEX - DEC2HEX",
    "DEC2OCT - DEC2OCT",
    "DEĞER - PRICE",
    "DEĞERİND - PRICEDISC",
    "DEĞERVADE - PRICEMAT",
    "DEĞİL - NOT",
    "DEĞİŞTİR - REPLACE",
    "DELTA - DELTA",
    "DERECE - DEGREES",
    "DETERMİNANT - MDETERM",
    "DEVRESEL_ÖDEME - PMT",
    "DEVRİK_DÖNÜŞÜM - TRANSPOSE",
    "DİZEY_TERS - MINVERSE",
    "DOĞRU - DOĞRU",
    "DOLAYLI - INDIRECT",
    "DOT - LINEST",
    "DÖRTTEBİRLİK - QUARTILE",
    "DÜŞEYARA - VLOOKUP",
    "EBOŞSA - ISBLANK",
    "EĞER - IF",
    "EĞERSAY - COUNTIF",
    "EĞİLİM - TREND",
    "EĞİM - SLOPE",
    "EHATA - ISERR",
    "EHATALIYSA - ISERROR",
    "ELEMAN - CHOOSE",
    "EMANTIKSALSA - ISLOGICAL",
    "EMETİNDEĞİLSE - ISNONTEXT",
    "EMETİNSE - ISTEXT",
    "ENÇOK_OLAN - MODE",
    "EREFSE - ISREF",
    "ESAYIYSA - ISNUMBER",
    "ETKİN - EFFECT",
    "ETOPLA - SUMIF",
    "EYOKSA - ISNA",
    "FAİZ_ORANI - RATE",
    "FAİZORANI - INTRATE",
    "FAİZTUTARI - IPMT",
    "FDAĞ - FDIST",
    "FISHER - FISHER",
    "FISHERTERS - FISHERINV",
    "FTERS - FINV",
    "FTEST - FTEST",
    "GAMADAĞ - GAMMADIST",
    "GAMALN - GAMMALN",
    "GAMATERS - GAMMAINV",
    "GD - FV",
    "GDPROGRAM - GDPROGRAM",
    "GEOORT - GEOMEAN",
    "GERÇEKFAİZ - ACCRINT",
    "GERÇEKFAİZV - ACCRINTM",
    "GETİRİ - RECEİVED",
    "GÜN - DAY",
    "GÜN360 - DAYS360",
    "GÜVENİRLİK - CONFIDENCE",
    "HAFTANINGÜNÜ - WEEKDAY",
    "HAFTASAY - WEEKNUM",
    "HARORT - HARMEAN",
    "HATA.TİPİ - ERROR.TYPE",
    "HATAİŞLEV - ERF",
    "HEX2BIN - HEX2BIN",
    "HEX2DEC - HEX2DEC",
    "HEX2OCT - HEX2OCT",
    "HİPERGEOMDAĞ - HYPGEOMDIST",
    "HTAHDEĞER - TBILLPRICE",
    "HTAHEŞ - TBILLEQ",
    "HTAHÖDEME - TBILLYIELD",
    "HÜCRE - CELL",
    "ISPMT - ISPMT",
    "İÇ_VERİM_ORANI - IRR",
    "İNDİRİM - DISC",
    "İNDİS - INDEX",
    "İŞARET - SIGN",
    "İŞGÜNÜ - WORKDAY",
    "KAÇINCI - MATCH",
    "KAREKÖK - SQRT",
    "KAREKÖKPİ - SQRTPI",
    "KARMAŞIK - COMPLEX",
    "KAYDIR - OFFSET",
    "KESMENOKTASI - INTERCEPT",
    "KIRP - TRIM",
    "KIRPORTALAMA - TRIMMEAN",
    "KİKAREDAĞ - CHIDIST",
    "KİKARETERS - CHIINV",
    "KİKARETEST - CHITEST",
    "KOD - CODE",
    "KOMBİNASYON - COMBIN",
    "KORELASYON - CORREL",
    "KOVARYANS - COVAR",
    "KÖPRÜ - HYPERLINK",
    "KRİTİKBİNOM - CRITBINOM",
    "KUPONGÜN - COUPDAYS",
    "KUPONGÜNBD - COUPDAYBS",
    "KUPONGÜNDSK - COUPDAYSNC",
    "KUPONGÜNÖKT - COUPPCD",
    "KUPONGÜNSKT - COUPNCD",
    "KUPONSAYI - COUPNUM",
    "KUVVET - POWER",
    "KÜÇÜK - SMALL",
    "KÜÇÜKHARF - LOWER",
    "KYUVARLA - MROUND",
    "LİRA - DOLLAR",
    "LİRAKES - DOLLARFR",
    "LİRAON - DOLLARDE",
    "LN - LN",
    "LOG - LOG",
    "LOG10 - LOG10",
    "LOGNORMDAĞ - LOGNORMDIST",
    "LOGTERS - LOGINV",
    "LOT - LOGEST",
    "M - T",
    "MAK - MAX",
    "MAKA - MAXA",
    "MBUL - SEARCH",
    "METNEÇEVİR - TEXT",
    "MİN - MIN",
    "MİNA - MINA",
    "MOD - MOD",
    "MSÜRE - MDURATION",
    "MUTLAK - ABS",
    "NBD - NPV",
    "NEGBİNOMDAĞ - NEGBINOMDIST",
    "NOMİNAL - NOMINAL",
    "NORMDAĞ - NORMDIST",
    "NORMSDAĞ - NORMSDIST",
    "NORMSTERS - NORMSINV",
    "NORMTERS - NORMINV",
    "NSAT - TRUNC",
    "OBEB - GCD",
    "OCT2BIN - OCT2BIN",
    "OCT2DEC - OCT2DEC",
    "OCT2HEX - OCT2OCT",
    "OKEK - LCM",
    "OLASILIK - PROB",
    "ORTALAMA - AVERAGE",
    "ORTALAMAA - AVERAGEA",
    "ORTANCA - MEDIAN",
    "ORTSAP - AVEDEV",
    "ÖDEME - YIELD",
    "ÖDEMEİND - YIELDDISC",
    "ÖDEMEVADE - YIELDMAT",
    "ÖZDEŞ - EXACT",
    "ÖZETVERİAL - GETPIVOTDATA",
    "PARÇAAL - MID",
    "PEARSON - PEARSON",
    "PERMÜTASYON - PERMUT",
    "Pİ - PI",
    "POISSON - POISSON",
    "RADYAN - RADIANS",
    "RANK - RANK",
    "RASTGELEARADA - RANDBETWEEN",
    "RKARE - RSQ",
    "ROMEN - ROMAN",
    "S - N",
    "S_SAYI_ÜRET - RAND",
    "SAAT - HOUR",
    "SAĞDAN - RIGHT",
    "SANAL - IMAGINARY",
    "SANBAĞ_DEĞİŞKEN - IMARGUMENT",
    "SANBÖL - IMDIV",
    "SANCOS - IMCOS",
    "SANÇARP - IMPRODUCT",
    "SANÇIKAR - IMSUB",
    "SANEŞLENEK - IMCONJUGATE",
    "SANGERÇEK - IMREAL",
    "SANİYE - SECOND",
    "SANKAREKÖK - IMSQRT",
    "SANKUVVET - IMPOWER",
    "SANLN - IMLN",
    "SANLOG10 - IMLOG10",
    "SANLOG2 - IMLOG2",
    "SANMUTLAK - IMABS",
    "SANSIN - IMSIN",
    "SANTOPLA - IMSUM",
    "SANÜS - IMEXP",
    "SAPKARE - DEVSQ",
    "SATIR - ROW",
    "SATIRSAY - ROWS",
    "SAYIDÜZENLE - FIXED",
    "SAYIYAÇEVİR - VALUE",
    "SERİAY - EDTE",
    "SERİTARİH - EOMONTH",
    "SERİTOPLA - SERIESSUM",
    "SIKLIK - FREQUENCY",
    "SİN - SIN",
    "SİNH - SINH",
    "SOLDAN - LEFT",
    "STANDARTLAŞTIRMA - STANDARDIZE",
    "STDSAPMA - STDEV",
    "STDSAPMAA - STDEVA",
    "STDSAPMAS - STDEVP",
    "STDSAPMASA - STDEVPA",
    "STHYX - STEYX",
    "SÜRE - DURATION",
    "SÜTUN - COLUMN",
    "SÜTUNSAY - COLUMNS",
    "ŞİMDİ - NOW",
    "TABANAYUVARLA - FLOOR",
    "TAHMİN - FORECAST",
    "TAKSİT_SAYISI - NPER",
    "TAMİŞGÜNÜ - NETWORKDAYS",
    "TAMSAYI - INT",
    "TAN - TAN",
    "TANH - TANH",
    "TARİH - DATE",
    "TARİHSAYISI - DATEVALUE",
    "TAVANAYUVARLA - CEILING",
    "TDAĞ - TDIST",
    "TEK - ODD",
    "TEKMİ - ISODD",
    "TEKSDEĞER - ODDLPRICE",
    "TEKSÖDEME - ODDLYIELD",
    "TEKYDEĞER - ODDFPRICE",
    "TEKYÖDEME - ODDFYIELD",
    "TEMİZ - CLEAN",
    "TOPANAPARA - CUMPRINC",
    "TOPKARE - SUMSQ",
    "TOPLA - SUM",
    "TOPLA.ÇARPIM - SUMPRODUCT",
    "TOPÖDENENFAİZ - CUMIMPT",
    "TOPX2AY2 - SUMX2PY2",
    "TOPX2EY2 - SUMX2MY2",
    "TOPXEY2 - SUMXMY2",
    "TTERS - TINV",
    "TTEST - TTEST",
    "TÜMHATAİŞLEV - ERFC",
    "TÜR - TYPE",
    "UZUNLUK - LEN",
    "ÜS - EXP",
    "ÜSTELDAĞ - EXPONDIST",
    "VAL - DGET",
    "VAR - VAR",
    "VARA - VARA",
    "VARS - VARP",
    "VARSA - VARPA",
    "VE - AND",
    "VSEÇÇARP - DPRODUCT",
    "VSEÇMAK - DMAX",
    "VSEÇMİN - DMIN",
    "VSEÇORT - DAVERAGE",
    "VSEÇSAY - DCOUNT",
    "VSEÇSAYDOLU - DCOUNTA",
    "VSEÇSTDSAPMA - DSTDEV",
    "VSEÇSTDSAPMAS - DSTDEVP",
    "VSEÇTOPLA - DSUM",
    "VSEÇVAR - DVAR",
    "VSEÇVARS - DVARP",
    "WEIBULL - WEIBULL",
    "YADA - OR",
    "YANLIŞ - YANLIŞ",
    "YAT - SYD",
    "YATAYARA - HLOOKUP",
    "YAZIM.DÜZENİ - PROPER",
    "YERİNEKOY - SUBSTITUTE",
    "YIL - YEAR",
    "YILORAN - YEARFRAC",
    "YİNELE - REPT",
    "YOKSAY - NA",
    "YUKARIYUVARLA - ROUNDUP",
    "YUVARLA - ROUND",
    "YÜZDEBİRLİK - PERCENTILE",
    "YÜZDERANK - PERCENTRANK",
    "ZAMAN - TIME",
    "ZAMANSAYISI - TIMEVALUE",
    "ZTEST - ZTEST",
  ];

  @override
  List<Widget> buildActions(BuildContext context) {
    return [
      IconButton(
          onPressed: () {
            query = '';
          },
          icon: const Icon(Icons.clear))
    ];
  }

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
        onPressed: () {
          close(context, null);
        },
        icon: const Icon(Icons.arrow_back));
  }

  @override
  Widget buildResults(BuildContext context) {
    List<String> matchQuery = [];
    for (var words in searchTerms) {
      if (words.toLowerCase().contains(query.toLowerCase())) {
        matchQuery.add(words);
      }
    }
    return ListView.builder(
      itemCount: matchQuery.length,
      itemBuilder: (context, index) {
        var result = matchQuery[index];
        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 5),
          child: ListTile(
            leading: const Icon(Icons.pageview_rounded),
            title: Text(
              result,
              style: GoogleFonts.raleway(),
            ),
          ),
        );
      },
    );
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    List<String> matchQuery = [];
    for (var words in searchTerms) {
      if (words.toLowerCase().contains(query.toLowerCase())) {
        matchQuery.add(words);
      }
    }
    return ListView.builder(
      itemCount: matchQuery.length,
      itemBuilder: (context, index) {
        var result = matchQuery[index];
        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 5),
          child: ListTile(
            leading: const Icon(Icons.pageview_rounded),
            title: Text(
              result,
              style: GoogleFonts.raleway(),
            ),
          ),
        );
      },
    );
  }
}
