// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7MWQaFiIRYKgNInERo4Vw51uHCBPTH6Y',
    appId: '1:235411455375:web:f1b887096735861ed29ffa',
    messagingSenderId: '235411455375',
    projectId: 'ehmobile-d464c',
    authDomain: 'ehmobile-d464c.firebaseapp.com',
    storageBucket: 'ehmobile-d464c.appspot.com',
    measurementId: 'G-43065ELB3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPBCIQNrihKRv2NJC-9uXYmi8zeor1m2I',
    appId: '1:235411455375:android:8f28a44c00687914d29ffa',
    messagingSenderId: '235411455375',
    projectId: 'ehmobile-d464c',
    storageBucket: 'ehmobile-d464c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI1hpdxKxvC8vW7h0w3U_QkX2FRGvUgZk',
    appId: '1:235411455375:ios:5e59da6d853f1e20d29ffa',
    messagingSenderId: '235411455375',
    projectId: 'ehmobile-d464c',
    storageBucket: 'ehmobile-d464c.appspot.com',
    iosClientId: '235411455375-67dd9hlrva69m8csvkli6lfg9q3jr01g.apps.googleusercontent.com',
    iosBundleId: 'com.example.excelHileleriMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI1hpdxKxvC8vW7h0w3U_QkX2FRGvUgZk',
    appId: '1:235411455375:ios:5e59da6d853f1e20d29ffa',
    messagingSenderId: '235411455375',
    projectId: 'ehmobile-d464c',
    storageBucket: 'ehmobile-d464c.appspot.com',
    iosClientId: '235411455375-67dd9hlrva69m8csvkli6lfg9q3jr01g.apps.googleusercontent.com',
    iosBundleId: 'com.example.excelHileleriMobil',
  );
}
